In [1]:
import matplotlib.pyplot as plt
import numpy as np
from IPython.display import clear_output
import multiprocessing as mp

In [2]:
import library
from importlib import reload
reload(library)

<module 'library' from '/home/jupyter-josh/contextualbandits/library.py'>

## Scratch but don't delete

In [1]:
import numpy as np
l =[.1,.2,.3]
X = np.random.randn(3,2)
s = 0
for i in range(3):
    s += l[i]*np.outer(X[i], X[i])
print(s)

print(X.T@np.diag(l)@X)

[[0.21876108 0.21473142]
 [0.21473142 0.30097   ]]
[[0.21876108 0.21473142]
 [0.21473142 0.30097   ]]


In [ ]:
U = [u1, u2, u3]
V = [v1,v2,v3].T
U@v = u1@v1.T + u2@v2.T + u3@v3.T

In [8]:
d = 5
V = np.eye(d)
X = np.random.randn(20,d)


In [11]:
X = X.reshape(20,1,d)
XT = X.reshape(20,d,1)

In [25]:
A = V + np.matmul(XT,X)

In [27]:
x = np.random.randn(d)

In [28]:
x@A@x

array([ 3.13103687,  3.00954796,  5.05600226,  3.79457384,  2.85755611,
        3.110461  ,  8.68935298,  2.73731387,  3.07675707,  5.63451737,
        2.90532333,  5.35543615,  2.90781363,  3.80364324,  2.64713931,
       16.7744548 , 11.24417744,  2.90006682,  4.76877344,  3.99901224])

In [30]:
x@(V+np.outer(X[1],X[1]))@x

3.0095479645977257

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

In [12]:
import numpy as np
#naive
d = 5
m = 6
X = np.random.randn(m,d)
V = np.random.randn(d,d)
y = np.random.randn(d)
outers = [np.outer(X[i], X[i]) for i in range(m)]
answers = [np.linalg.inv(V+o) for o in outers]
print(answers)
print([y@a@y for a in answers])

# batch mm
B = np.matmul(X.reshape(-1,d,1),X.reshape(-1,1,d))
print(np.linalg.inv(V+B))
print(y@np.linalg.inv(V+B)@y)

[array([[ 0.64379922,  0.99796802, -0.43479827, -0.61607403,  0.20176494],
       [-0.19630807, -0.76113886, -0.52656992,  0.78996645, -0.23293603],
       [-0.68520025,  0.92259753,  0.45881859, -1.07174366,  0.14335746],
       [-1.60947667,  0.94225369,  1.72156485, -1.09298893, -0.1849969 ],
       [ 1.13989356, -0.43538073, -1.0750386 ,  0.72402914,  0.40453262]]), array([[ 0.29138017, -0.12993127, -0.36492756, -0.06209217,  0.3254481 ],
       [-0.35182195, -0.99014891, -0.47237372,  0.98604073, -0.19791698],
       [-0.21454549,  2.2735439 ,  0.35199778, -1.78361003, -0.01051223],
       [-0.46665902,  4.22878634,  1.46273109, -2.82262676, -0.55906892],
       [ 0.14231923, -2.57814468, -0.78596799,  2.10310222,  0.67821109]]), array([[-0.32686922,  2.74218333,  0.85255479, -2.70436693, -0.87179723],
       [-0.57444037, -0.1665881 , -0.06175563,  0.11104601, -0.59877921],
       [ 0.48723865, -1.05056805, -1.03841412,  1.2388751 ,  1.35767772],
       [ 1.10245611, -3.48717234,

[[[-1.82768086e+00 -1.88919887e+00  1.40503544e-01  1.17986714e+00
   -8.58333561e-01]
  [-3.17832053e+00 -3.49183531e+00  1.22770011e+00  3.69537143e+00
   -1.71614714e+00]
  [-1.24417760e+00 -1.53287785e+00  3.98746861e-01  1.99048861e+00
   -7.82848992e-01]
  [ 2.10218141e+00  2.49896548e+00 -5.39273807e-01 -2.09942882e+00
    1.81393014e+00]
  [-5.44027282e-01  3.17045744e-01 -7.75928305e-02  1.73756879e-01
   -3.28229894e-01]]

 [[-3.61450913e-01  8.96632267e-02  1.69721273e-01  4.65171504e-01
    3.73569136e-01]
  [-2.15450369e-02  6.46493051e-02 -1.38574797e-01 -1.69281199e-01
   -3.74043138e-01]
  [ 1.68567451e-01 -5.59858426e-02 -4.45625181e-01 -1.18126814e-01
   -3.95749440e-01]
  [ 3.23646264e-01  2.23501601e-01 -3.21163893e-01 -8.19861980e-01
    5.52070616e-01]
  [-3.32203138e-01  2.04321631e-01 -8.82600112e-01 -1.24647393e+00
   -8.92099869e-01]]

 [[-4.06726002e-01 -1.05791873e-02  1.73156659e-01  5.41130443e-01
    4.02492985e-01]
  [ 9.08926737e-01  1.92914656e+00  1.3

In [7]:
from library import FW
import numpy as np
X = np.random.randn(20, 5)
ans = FW(X,X, step_size=1)
print(max(ans[1]))


5.0012398222639245


In [14]:
class A:
    def __init__(self):
        print(5)
        
A.__name__

'A'