In [1]:
import numpy as np

In [16]:
d = 5
m = 6
X = np.random.randn(m,d)
V = np.random.randn(d,d)
y = np.random.randn(d)

In [13]:
#naive naive
outers = [np.outer(X[i], X[i]) for i in range(m)]
V_inv = np.linalg.inv(np.sum(outers) + )
y @ V_inv @ y

[[ 0.80200239 -0.19799761 -0.19799761 -0.19799761 -0.19799761]
 [-0.19799761  0.80200239 -0.19799761 -0.19799761 -0.19799761]
 [-0.19799761 -0.19799761  0.80200239 -0.19799761 -0.19799761]
 [-0.19799761 -0.19799761 -0.19799761  0.80200239 -0.19799761]
 [-0.19799761 -0.19799761 -0.19799761 -0.19799761  0.80200239]]


In [19]:
#naive
outers = [np.outer(X[i], X[i]) for i in range(m)]
answers = [np.linalg.inv(V+o) for o in outers]
print(answers)
print([y @ a @ y for a in answers])

[array([[ 0.23367066,  0.09438807,  0.1766209 , -0.12999618,  0.04534253],
       [-0.9108921 ,  1.41668534, -0.5732616 , -1.2073832 , -0.25543458],
       [-1.63450578,  2.0270996 , -0.43519957, -0.99855994, -1.17028026],
       [ 1.56409426, -1.79888276,  0.59186041,  1.74186693,  0.90038056],
       [ 0.49670118, -0.34584034,  0.35065122, -0.13954433,  0.72889455]]), array([[ 0.36192201,  0.23711225, -0.07514346, -0.35934988,  0.02745031],
       [ 0.14430344,  0.70852393, -0.30892652, -0.82462021,  0.3869316 ],
       [ 0.08864916,  0.85707663,  0.01331686, -0.35712427, -0.11558704],
       [ 0.10292084, -0.41054419, -0.28007569,  0.72022445, -0.16014562],
       [-0.29378036, -0.12879336,  0.5415733 , -0.04832357,  0.37915593]]), array([[ 0.29317223,  0.85909771, -0.52915529, -0.9166711 , -0.20265419],
       [ 0.42246437, -2.68974866,  1.99238173,  2.12626152,  1.5669606 ],
       [ 0.15667925, -1.76521268,  1.51951069,  1.77838636,  0.67889956],
       [ 0.13449738,  1.57239884,

In [18]:
# batch mm
B = np.matmul(X.reshape(-1,d,1),X.reshape(-1,1,d))
print(np.linalg.inv(V+B))
print(y@np.linalg.inv(V+B)@y)

[[[ 2.33670661e-01  9.43880744e-02  1.76620902e-01 -1.29996183e-01
    4.53425265e-02]
  [-9.10892097e-01  1.41668534e+00 -5.73261597e-01 -1.20738320e+00
   -2.55434579e-01]
  [-1.63450578e+00  2.02709960e+00 -4.35199575e-01 -9.98559939e-01
   -1.17028026e+00]
  [ 1.56409426e+00 -1.79888276e+00  5.91860413e-01  1.74186693e+00
    9.00380562e-01]
  [ 4.96701179e-01 -3.45840343e-01  3.50651221e-01 -1.39544334e-01
    7.28894548e-01]]

 [[ 3.61922005e-01  2.37112247e-01 -7.51434599e-02 -3.59349882e-01
    2.74503077e-02]
  [ 1.44303437e-01  7.08523925e-01 -3.08926523e-01 -8.24620207e-01
    3.86931598e-01]
  [ 8.86491628e-02  8.57076635e-01  1.33168648e-02 -3.57124267e-01
   -1.15587038e-01]
  [ 1.02920840e-01 -4.10544188e-01 -2.80075689e-01  7.20224445e-01
   -1.60145616e-01]
  [-2.93780363e-01 -1.28793356e-01  5.41573302e-01 -4.83235702e-02
    3.79155927e-01]]

 [[ 2.93172232e-01  8.59097708e-01 -5.29155291e-01 -9.16671100e-01
   -2.02654192e-01]
  [ 4.22464375e-01 -2.68974866e+00  1.9

In [17]:
import numpy as np

def pairwise_diff(arr):
    """Compute all unique pairwise differences between elements in a numpy array"""
    # Reshape the input array as a column vector
    arr = arr.reshape((-1, 1))
    # Compute the differences between all pairs of elements
    diffs = arr - arr.T
    # Return the unique non-zero differences
    return np.unique(diffs[np.nonzero(diffs)])

# Example usage:
arr = np.array([1, 2, 3])
diffs = pairwise_diff(arr)
print(diffs)

[-2 -1  1  2]


In [7]:
np.array([1, 2, 3]).reshape((-1, 1))

array([[1],
       [2],
       [3]])

In [8]:
np.array([1, 2, 3]).reshape((-1, 1)).T

array([[1, 2, 3]])

In [10]:
np.nonzero(np.array([[1],[2],[3]]) - np.array([[1, 2, 3]]))

(array([0, 0, 1, 1, 2, 2]), array([1, 2, 0, 2, 0, 1]))

In [21]:
np.sum([0.00000000e+00, 1.67664671e-04, 2.51497006e-04, 8.38323353e-05, 1.67664671e-04, 1.67664671e-04, 1.67664671e-04, 0.00000000e+00, 0.00000000e+00, 8.38323353e-05, 1.67664671e-04, 8.38323353e-05, 8.38323353e-05, 0.00000000e+00, 8.38323353e-05, 8.38323353e-05,0.00000000e+00, 8.38323353e-05, 0.00000000e+00, 0.00000000e+00])

0.0016766467081

In [31]:
# n = 
# inds = np.random.choice(n, 2*d, p=1/n * np.ones(n)).tolist()
lam = np.bincount(inds, minlength=4) / len(inds)
np.sum(lam)

ValueError: object of too small depth for desired array